### ISSUE TITLE
请教下属性authorize()中请求后台获取用户信息的code怎么获取？报code is not defined，这个变量啊，前面又没有定义

### ISSUE THREAD

**Issue by bigbigbigbear** [raychenfj/v-wechat-auth#1]
请教下属性authorize()中请求后台获取用户信息的code怎么获取？报code is not defined，这个变量啊，前面又没有定义，就是params{code:code}里这个code怎么来的，报错了

**Comment by meta-bowen** [comment]
请问您解决了吗 我也遇到了同样的问题  若解决了望您分享于此，谢谢
